language: android

before_install: cd HelloWorld
jdk: oraclejdk7

env:
  global:
    - TERM=dumb
  matrix:
    #ANDROID_SDKS=android-23,sysimg-23  ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23.0 ANDROID_ABI=armeabi-v7a

android:
  components:
    - android-23.0
    - build-tools-23.0

#script: gradle build
install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check
