 language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0

    # The SDK version used to compile your project
    - android-23

before_install: 

  - wget http://services.gradle.org/distributions/gradle-2.4-all.zip
  - unzip -q -o gradle:2.4-all.zip
  - export PATH="${BASEDIR}/gradle:2.4/bin:${PATH}"
  - cd HelloWorld


jdk: oraclejdk7

env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

 script: gradle build 
