 language: android

before_install: 

 - wget http://services.gradle.org/distributions/gradle-2.8-all.zip
  - unzip -q -o gradle:2.8-all.zip
  - export PATH="${BASEDIR}/gradle:2.8/bin:${PATH}"
  - cd HelloWorld


jdk: oraclejdk7

env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

 script: gradle build 
