language: android

before_install: 
 - wget https://downloads.gradle.org/distributions-snapshots/gradle-2.8-20150817220036 0000-all.zip
 - unzip -q -o gradle:2.8-20150817220036 0000-all.zip
 - export PATH="${BASEDIR}/g2.8-20150817220036 0000/bin:${PATH}"
 - cd HelloWorld



jdk: oraclejdk7

env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

 script: gradle build 
