language: android

before_install: 
  - cd HelloWorld
  - wget http://services.gradle.org/distributions/gradle-2.8-bin.zip
  - unzip gradle-2.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.8
  - export PATH=$GRADLE_HOME/bin:$PATH
  
jdk: oraclejdk7

env:
  global:
    - TERM=dumb

#script: gradle build
install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check

