language: android
jdk: oraclejdk7

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - mksdcard 50M /tmp/sdcard.img
  - emulator -avd test -no-skin -no-audio -no-window -prop persist.sys.language=en -prop persist.sys.country=US -sdcard /tmp/sdcard.img &
  

script: ./gradlew connectedAndroidTest
