 language: android

before_install: 

 - wget http://services.gradle.org/distributions-snapshots/gradle-2.8-20150817220036 0000-all.zip
  - unzip gradle-2.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.8
  - export PATH=$GRADLE_HOME/bin:$PATH
  - export  KEYSTORE=$HOME/snowdream.keystore
  - export  KEYSTORE_PASSWORD=1234567
  - export  KEY_ALIAS=snowdream
  - export  KEY_PASSWORD=1234567
  - cd HelloWorld


jdk: oraclejdk7

env:
  global:
    - TERM=dumb
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

 script: gradle build 
