
language: android

jdk: oraclejdk7

android:
  components:
    - tools
    - android-23.0
    - extra-android-support
    - extra-android-m2repository

env:
  matrix:
    - ANDROID_TARGET=android-23.0  ANDROID_ABI=armeabi-v7a
 
install:
    - true

script: 
   - TERM=dumb ./gradlew test assembleDebug
   #- TERM=dumb ./gradlew assembleDebug
   #- TERM=dumb ./gradlew assembleDebug -PdisablePreDex
   #- TERM=dumb ./gradlew test assembleDebug -PdisablePreDex
   #- TERM=dumb ./gradlew build connectedCheck
   #- TERM=dumb ./gradlew check


