language: android

jdk: oraclejdk7

android:
  components:
    - tools
    - android-23.0
    - extra-android-support
    - extra-android-m2repository

env:
  matrix:
    - ANDROID_TARGET=android-23.0  ANDROID_ABI=armeabi-v7a

install:
  - TERM=dumb ./gradlew assemble

before_script:
  # Make sure the emulator has started before running tests

 - chmod +x wait_for_emulator
 - ./wait_for_emulator
 
script: ./gradlew connectedAndroidTest
